# Generated by Django 4.2.3 on 2023-07-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Expenses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("PlaceName", models.CharField(max_length=20)),
                ("Items", models.CharField(max_length=200)),
                ("Catogries", models.CharField(max_length=20)),
                ("Amount", models.FloatField(max_length=15)),
            ],
        ),
    ]
