# Generated by Django 4.2.3 on 2023-07-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlaceName', models.CharField(max_length=30)),
                ('Amount', models.FloatField(max_length=10)),
                ('Categoty', models.CharField(max_length=30)),
                ('Image', models.CharField(max_length=50)),
            ],
        ),
    ]
