# Generated by Django 4.2.3 on 2023-07-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expenses", name="Date", field=models.DateField(auto_now=True),
        ),
    ]
