# Generated by Django 4.2.3 on 2023-07-25 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expenses",
            name="Category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Category",
                to="app.category",
            ),
        ),
        migrations.AlterField(
            model_name="expenses",
            name="recipet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Recipt",
                to="app.recipet",
            ),
        ),
    ]
