# Generated by Django 4.2.3 on 2023-07-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipet',
            name='Categoty',
            field=models.FileField(max_length=30, upload_to=''),
        ),
    ]
