# Generated by Django 4.2.3 on 2023-07-24 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_expenses_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expenses",
            name="Category",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Category",
                to="app.category",
            ),
            preserve_default=False,
        ),
    ]
