# Generated by Django 4.2.3 on 2023-07-23 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_expenses_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="expenses",
            name="recipet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Recipt",
                to="app.recipet",
            ),
        ),
    ]
