# Generated by Django 4.2.3 on 2023-07-21 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_recipet_categoty_alter_recipet_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipet',
            name='Image',
        ),
    ]
