# Generated by Django 4.2.3 on 2023-07-21 10:57

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_recipet_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipet',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.upload_to),
        ),
    ]
