# Generated by Django 4.2.3 on 2023-07-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='budget',
            field=models.FloatField(blank=True),
        ),
    ]
