# Generated by Django 4.2.3 on 2023-07-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_remove_user_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='budget',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
